baseURL = 'https://tinytapeout.com'
languageCode = 'en-us'
title = 'Tiny Tapeout'
theme = "learn"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
